FROM node:20-alpine3.18 AS builder
WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine3.18
WORKDIR /app

COPY ./package*.json ./

RUN npm ci --omit=dev --ignore-scripts

EXPOSE 3000 

COPY --from=BUILDER /app/dist ./

CMD ["node", "main.js"]